### ISSUE TITLE
Counterfactuals printing something but not right thing

### ISSUE THREAD

**Issue by mbuit82** [benbrastmckie/ModelChecker#52] opened 2024-10-31 18:53 UTC
I got the CF operator to work in the sense that it runs to completion and can find models. The entire printing apparatus is not done yet either (thought I'd work on that after getting it to work. But the results are definitely not right because these inputs give a model when (I'm pretty sure) they shouldn't: 
```
premises = ["A", "(A \\boxright B)"]
conclusions = ["B"]
```
A couple other rules of inference for CFs are also broken. I couldn't really figure out where it went wrong; I suspect it's a semantic definition or something in some `find_verifiers_and_falsifiers` (maybe the one I wrote to get it to work, in the CF operator).

**Comment by benbrastmckie** [comment] 2024-10-31 20:28
It's looks good, but I see what you mean about the models that it is finding. I poked around but nothing obvious jumped out. Given that it is working (no errors), one thought for how to proceed is to work on printing since this will help us see what is going wrong and hopefully will be pretty much the same as before so hopefully easy. Another thought is to integrate printing for constraints so that we can check to see what constraints it is generating since it must not be getting those totally right. I'll keep poking but hopefully the solution will bubble up by improving the printing so that we can see what the alt worlds are, and what is true in each, etc.

One other observation is that the example you used is a good choice because it only uses \boxright, so there is no risk that the problem is to do with other operators. It seems more likely that it is something to do with the way it is evaluating sentences at worlds. I wonder if it somehow isn't getting the right worlds. Improving the clarity and consistency of the way sentences are evaluated at worlds and states (or checking this) could be another indirect way to try to find the problem.

I'll keep poking around as well.

**Comment by mbuit82** [comment] 2024-10-31 22:02
I added a block of code to `test_example` that tries to help at debugging. I think it should be useful for figuring out whether the right thing is going on. Basically, it goes through every verifier of A, then at every world it asks if that world is a verifier-alternative to the main world. The results are that none of the worlds are verifier-alternatives to the main world for any verifier of A. You may want to double check that the code is in fact doing what it's supposed to (it's rather short—I'm mostly concerned about my use of `is_alternative`). I have to go right now somewhere but I think this may be helpful (and in any case you'll likely be much faster at finding the error if this is the right place to look since you know the system much better). My thought was that the main world should be a v-alternative to itself for some v in A's verifiers, and that would make B true at the main world, meaning the entailment is true (if I'm getting the intuition for this CF MP of sorts right)

**Comment by benbrastmckie** [comment] 2024-10-31 22:24
Looks very useful! I'll take a look and see if I can figure out what was going wrong. I managed to remove `operator_collection` from `Sentence`. To do so, I ended up having to change around a bunch of things which I'll report on in a new issue. But happy to switch to working on the CF semantics.

**Comment by mbuit82** [comment] 2024-10-31 23:38
Sounds good! I think I fixed the CF issue. Here was the old definition of `is_alternative` in the semantics:
```
def is_alternative(self, bit_u, bit_y, bit_w):
        """
        bit_u is a world that is the alternative that results from imposing state bit_y on
        world bit_w.
        returns a Z3 constraint
        """
        z = z3.BitVec("alt_z", self.N)
        return z3.And(
            self.is_world(bit_u),
            self.is_part_of(bit_y, bit_u),
            z3.And(self.is_part_of(z, bit_u), self.max_compatible_part(z, bit_w, bit_y)),
        )
```

It seemed to me off the top of my head that the third conjunct should have an existential quantifier. So changed to look like this: 
```
def is_alternative(self, bit_u, bit_y, bit_w):
        """
        bit_u is a world that is the alternative that results from imposing state bit_y on
        world bit_w.
        returns a Z3 constraint
        """
        z = z3.BitVec("alt_z", self.N)
        return z3.And(
            self.is_world(bit_u),
            self.is_part_of(bit_y, bit_u),
            Exists(z, z3.And(self.is_part_of(z, bit_u), self.max_compatible_part(z, bit_w, bit_y))),
        )
```
Now the CF MP does not give a model (as desired), and seems that other things work more reasonably. Another indication that it's actually working now is that if you do conclusion neg B with premise A boxright B, each proposition will have verifiers and falsifiers, thus making use of the hyperintensionality, not like before where everything was either a verifier or a falsifier (which seemed to basically project down to an extensional system, which makes sense, but not when boxright was in the mix)

**Comment by mbuit82** [comment] 2024-10-31 23:42
new issue though: no model found for the following inputs: 
```
premises = ["(A \\boxright B)", "(B \\boxright C)"]
conclusions = ["(A \\boxright C)"]
```
At least if I remember correctly there should be a model being found for this right?

**Comment by benbrastmckie** [comment] 2024-11-01 12:54
Yes, it was finding a countermodel with N=3. I merged our branch into master since we are working in a new directory anyhow and I'm thinking of testing some changes on a new branch to avoid conflicts. The semantic definitions all look good but I'll keep poking around.

**Comment by benbrastmckie** [comment] 2024-11-01 13:36
I tried this example:
```
premises = ["A", "(A \\boxright B)"]
conclusions = ["(A \\boxright C)"]
```
It also failed to find a countermodel. So the issue is pretty fundamental (so hopefully easier to find). Since we are starting to move into diagnostics, it is probably time to set up unit testing to streamline the process. I imagine most of this can be easily adapted from before.

I looked back to an old commit on master before we got going with the new branch and there are some differences. I'm not sure where they are coming from, but here is one example comparing definitions from the current commit to the past:
```
def define_N_semantics(verify, falsify, possible, assign, N): # from the current commit
    ...

def define_N_semantics(N, contingent, disjoint, verify, falsify, possible, imposition): # fron commit 1c72f893
    ...
```
As a result of these differences, the old unit tests don't work on our current commit. I will try to fix this by updating our old files in `model_checker` while leaving `new_checker` as it is.

Also, I looked through the constraints and it is a lot to parse. Given that it is running, the best strategy may be to continue working on printing alt worlds ect., since this will help us see what is going wrong.

**Comment by benbrastmckie** [comment] 2024-11-01 14:25
I stashed the version of the modules that came from the branch we were working on in `model_checker_save`. The unit tests didn't run on this version, so maybe not needed.

**Comment by benbrastmckie** [comment] 2024-11-01 14:34
I had another idea: to compare our current version with the old (unit tests are all working for the old version), we could define a test which uses both the old and new model-checkers to generate separate sets of constraints in order to look for discrepancies. This assumes that all our variables are named in the same way which might not be totally true but not too hard to change.

**Comment by mbuit82** [comment] 2024-11-05 20:43
I think I've made some progress: the `model_checker` definition of `Exists` (`FiniteExists`, in `semantics.py` lines 62-81) had a recursive call to itself at line 77. However the `new_checker` definition of `Exists` had a call to `ForAll`, not to `Exists`. I changed this and it seems better models are being made. 

The two theorems I'm using as reference are transitivity and weakened transitivity: 
```
premises = ["(A \\boxright B)", "(B \\boxright C)"]
conclusions = ["(A \\boxright C)"]
```
and 
```
premises = ["(A \\boxright B)", "((A \\wedge B) \\boxright C)"]
conclusions = ["(A \\boxright C)"]
```
respectively. I'm getting a model for the Transitivity (as desired), but I'm also getting a model for the Weakened Transitivity (not desired). (SDA gets a model as desired and STA does not as desired for what it's worth.) I think the model for Transitivity looks right; the model for Weakened Transitivity looks ver similar to Transitivity's. I've set all these inputs (T, WT, SDA, STA) in `example.py` for easy testing.

**Comment by benbrastmckie** [comment] 2024-11-05 21:03
That's great! Nice find! I added a bunch of examples but feel free to move things around. I created labels for working/not-working. I'll keep poking around.

**Comment by benbrastmckie** [comment] 2024-11-05 21:32
Just went back through the examples and seems like we are down to 2 that are not working and 22 that are working (just focusing on counterfactuals for now). So that's great! The one's that are not working seems to be from a small bug. 

I also noticed that it is running much faster than before. I don't know what explains this, but it's great news! Would have been pretty sad if it worked but was way slower than before.

**Comment by mbuit82** [comment] 2024-11-05 22:56
That's great—good it's getting faster not slower! Which are the two that don't work?

**Comment by benbrastmckie** [comment] 2024-11-06 04:53
I fixed the error in the two but was wrong that weakened transitivity is working. The print statements are really helpful:
```
State Space:
  #b000 = □
  #b001 = a
  #b010 = b
  #b011 = a.b (impossible)
  #b100 = c
  #b101 = a.c (world)
  #b110 = b.c (world)
  #b111 = a.b.c (impossible)

The evaluation world is: a.c

INTERPRETED PREMISES:

1.  |(A \boxright B)| = < {□}, ∅ >  (True in a.c)
  |A| = < {a.b, a.b.c, b.c}, {a.c} >  (False in a.c)
  A-alternatives to a.c = {b.c}
    |B| = < {b, b.c}, {a} >  (True in b.c)

2.  |((A \wedge B) \boxright C)| = < {□}, ∅ >  (True in a.c)
  |(A \wedge B)| = < {a.b, a.b.c, b.c}, {a, a.c} >  (False in a.c)
    |A| = < {a.b, a.b.c, b.c}, {a.c} >  (False in a.c)
    |B| = < {b, b.c}, {a} >  (False in a.c)
  (A \wedge B)-alternatives to a.c = {b.c}
    |C| = < ∅, {a.b.c, c} >  (False in b.c)

INTERPRETED CONCLUSION:

3.  |(A \boxright C)| = < ∅, {□} >  (False in a.c)
  |A| = < {a.b, a.b.c, b.c}, {a.c} >  (False in a.c)
  A-alternatives to a.c = {b.c}
    |C| = < ∅, {a.b.c, c} >  (False in b.c)
```

Somehow it is making the second premise true even though `C` is false in `b.c`. It does better with the conclusion, but something is off. In any case, it seems like it is not far off.

**Comment by benbrastmckie** [comment] 2024-11-06 05:01
Found the bug in `extended_verify` for `AndOperator`. It used to be:
```
    def extended_verify(self, state, leftarg, rightarg, eval_world):
        y = z3.BitVec("ex_ver_y", self.semantics.N)
        z = z3.BitVec("ex_ver_z", self.semantics.N)
        return z3.And(
            self.semantics.fusion(y, z) == state,
            self.semantics.extended_verify(y, leftarg, eval_world),
            self.semantics.extended_verify(z, rightarg, eval_world),
        )
    
```
And now it reads:
```
    def extended_verify(self, state, leftarg, rightarg, eval_world):
        x = z3.BitVec("ex_ver_x", self.semantics.N)
        y = z3.BitVec("ex_ver_y", self.semantics.N)
        return Exists(
            [x, y],
            z3.And(
                self.semantics.fusion(x, y) == state,
                self.semantics.extended_verify(x, leftarg, eval_world),
                self.semantics.extended_verify(y, rightarg, eval_world),
            )
        )
```
The `extended_falsify` in `OrOperator` (which is the dual) included `Exists`, and so was already correct.

**Closed** 2024-11-06 05:23 UTC
